In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[0:5] = 100

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
arr_2d[1]

array([20, 25, 30])

In [16]:
arr_2d[0]

array([ 5, 10, 15])

In [17]:
arr_2d[1][2]

30

In [18]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [20]:
arr2d = np.zeros((3,3))

In [21]:
arr2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr_length = arr2d.shape[1]

In [23]:
arr_length

3

In [31]:
for i in range(arr_length):
    arr2d[i]=1

In [32]:
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
for i in range(arr_length):
    arr2d[i]=i

In [34]:
arr2d

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [36]:
arr2d[[0,2]]

array([[0., 0., 0.],
       [2., 2., 2.]])

In [39]:
arr2d[:,[0,2]]

array([[0., 0.],
       [1., 1.],
       [2., 2.]])