In [7]:
import numpy as np

In [8]:
my_list1 = [1,2,3,4]

In [9]:
my_array1 = np.array(my_list1)

In [10]:
my_array1

array([1, 2, 3, 4])

In [11]:
my_list2 = [11,22,33,44]

In [12]:
my_lists = [my_list1, my_list2]

In [13]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [14]:
my_array2 = np.array(my_lists)

In [15]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [16]:
my_array2.shape

(2, 4)

In [17]:
my_array2.dtype

dtype('int32')

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
my_zeros_array = np.zeros(5)

In [20]:
my_zeros_array.dtype

dtype('float64')

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty(5)

array([9.85330622e+165, 1.09865413e+248, 6.96407597e+252, 1.97717802e+161,
       6.01334541e-154])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [26]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])