In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 0.95674315, -0.45588844,  1.8042879 , -2.00890491,  1.31789592,
       -2.04885862, -0.15693239, -0.21606192, -0.47260273,  0.39452391])

In [7]:
B = np.random.randn(10)
B

array([ 0.68325442, -0.60398396, -0.2948029 ,  1.55098196, -1.68859195,
        0.179384  ,  0.2913683 ,  1.28642377, -0.67548072, -1.0518163 ])

In [8]:
#Binary Functions
np.add(A,B)

array([ 1.63999757, -1.0598724 ,  1.509485  , -0.45792295, -0.37069602,
       -1.86947463,  0.13443591,  1.07036185, -1.14808345, -0.65729239])

In [9]:
np.maximum(A,B)

array([ 0.95674315, -0.45588844,  1.8042879 ,  1.55098196,  1.31789592,
        0.179384  ,  0.2913683 ,  1.28642377, -0.47260273,  0.39452391])

In [10]:
website = 'https://docs.scipy.org/doc/numpy/user/basics.html'
import webbrowser
webbrowser.open(website)

True